version: 1.0.{build}
image: Visual Studio 2019 Preview
environment:
  APPVEYOR_RDP_PASSWORD: DaveLithgow1980

init:
  - ps: |

      iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - ps: |

      echo content ...
      
      dir
      
      echo docker info...
      
      docker info
      
      echo docker images list...
      
      docker images list
      
      echo get-content dockerfile.noplatform | docker build -
      
      get-content dockerfile.noplatform | docker build -
      
      echo docker images list...\ndocker images list
      
      echo get-content dockerfile.platform | docker build -
      
      Get-Content dockerfile.platform | docker build -
      
      echo docker images list... 
      
      docker images list
      
     
      

on_finish:
  - ps: |

      $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

