# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: WindowsNoPlatform
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker version
      docker info
      docker images list
      get-content .\dockerfile.noplatform | docker build -
      docker images list
    displayName: 'Run all-the-things!'
- job: WindowsPlatform
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker version
      docker info
      
      docker images list
      get-content .\dockerfile.platform | docker build -
      docker images list
    displayName: 'Run all-the-things!'
- job: WindowsPlatformPlusOne
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker version
      docker info
      # https://www.altaro.com/msp-dojo/linux-containers-windows-server-2019/
      [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
      Restart-Service docker

      $hyperv = Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
      # Check if Hyper-V is enabled
      if($hyperv.State -eq "Enabled") {
          Write-Host "Hyper-V is enabled."
      } else {
          Write-Host "Hyper-V is disabled."
      }

      docker version
      docker info

      docker images list
      get-content .\dockerfile.platform | docker build -
      docker images list
    displayName: 'Run all-the-things!'
- job: WindowsPlatformPlusTwo
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker version
      docker info
      # https://computingforgeeks.com/how-to-run-docker-containers-on-windows-server-2019/
      Uninstall-Package -Name docker -ProviderName DockerMSFTProvider
      Get-VM WinContainerHost | Set-VMProcessor -ExposeVirtualizationExtensions $true
      Install-Module DockerProvider
      Install-Package Docker -ProviderName DockerProvider -RequiredVersion preview

      [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
      Restart-Service docker


      $hyperv = Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
      # Check if Hyper-V is enabled
      if($hyperv.State -eq "Enabled") {
          Write-Host "Hyper-V is enabled."
      } else {
          Write-Host "Hyper-V is disabled."
      }

      docker version
      docker info
      
      docker images list
      get-content .\dockerfile.platform | docker build -
      docker images list
    displayName: 'Run all-the-things!'
- job: WindowsPlatformPlusThree
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker version
      docker info
      # https://bcthomas.com/2019/02/getting-started-with-linux-containers-on-windows-server-2019/
      Install-Module DockerMSFTProvider
      Import-Module -Name DockerMSFTProvider -Force
      Import-Packageprovider -Name DockerMSFTProvider -Force
      Find-Package docker
      Install-Package -Name Docker -Source DockerDefault 
      # Set LCOW_SUPPORTED Variable to 1 for enabled
      [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
      
      # Enable Experimental Features in Dockerd daemon.conf
      $configfile = @"
      {
          "experimental": true
      }
      "@
      $configfile|Out-File -FilePath C:\ProgramData\docker\config\daemon.json -Encoding ascii -Force
      Invoke-WebRequest -Uri "https://github.com/linuxkit/lcow/releases/download/v4.14.35-v0.3.9/release.zip" -UseBasicParsing -OutFile release.zip
      Expand-Archive release.zip -DestinationPath "$Env:ProgramFiles\Linux Containers\."

      Restart-Service docker

      
      $hyperv = Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
      # Check if Hyper-V is enabled
      if($hyperv.State -eq "Enabled") {
          Write-Host "Hyper-V is enabled."
      } else {
          Write-Host "Hyper-V is disabled."
      }

      
      docker version
      docker info

      docker images list
      get-content .\dockerfile.platform | docker build -
      docker images list
    displayName: 'Run all-the-things!'

