# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Windows-NoPlatform
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker info
      docker images list
      get-content .\dockerfile.noplatform | docker build -
      docker images list
    displayName: 'Run all-the-things!'
- job: Windows-Platform
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker info
      docker images list
      get-content .\dockerfile.platform | docker build -
      docker images list
    displayName: 'Run all-the-things!'

