# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - pwsh: |
      dir
      $configfile = '{ "experimental":true }'
      $configfile|Out-File -FilePath c:\\Programdata\\docker\\config\\daemon.json -Encoding ascii -Force 
      more c:\\Programdata\\docker\\config\\daemon.json
      restart-Service docker
      docker info
      docker build -f dockerfile.noplatform
      docker images list
      docker build -f dockerfile.platform
      docker images list
    displayName: 'Run all-the-things!'

