# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - pwsh: |

      Install-Module DockerMSFTProvider
      Import-Module -Name DockerMSFTProvider -Force
      Import-Packageprovider -Name DockerMSFTProvider -Force
      Find-Package docker
      Install-Package -Name Docker -Source DockerDefault 
      # Set LCOW_SUPPORTED Variable to 1 for enabled
      [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
      
      # Enable Experimental Features in Dockerd daemon.conf
      $configfile = @"
      {
          "experimental": true
      }
      "@
      $configfile|Out-File -FilePath C:\\ProgramData\\docker\\config\\daemon.json -Encoding ascii -Force
      Invoke-WebRequest -Uri "https://github.com/linuxkit/lcow/releases/download/v4.14.35-v0.3.9/release.zip" -UseBasicParsing -OutFile release.zip
      Expand-Archive release.zip -DestinationPath "$Env:ProgramFiles\Linux Containers\."

      dir
      $configfile = '{ "experimental":true }'
      $configfile|Out-File -FilePath c:\\Programdata\\docker\\config\\daemon.json -Encoding ascii -Force 
      more c:\\Programdata\\docker\\config\\daemon.json
      Invoke-WebRequest -UseBasicParsing -OutFile dockerd.exe https://master.dockerproject.org/windows/x86_64/dockerd.exe
      Invoke-WebRequest -UseBasicParsing -OutFile docker.exe https://master.dockerproject.org/windows/x86_64/docker.exe
      dir
      Invoke-WebRequest -UseBasicParsing -OutFile release.zip https://github.com/linuxkit/lcow/releases/download/v4.14.35-v0.3.9/release.zip
      dir
      Expand-Archive release.zip -DestinationPath "$Env:ProgramFiles\Linux Containers\."
      docker info
      rm release.zip
      Enable-WindowsOptionalFeature Containers,Hyper-V
      restart-Service docker
      docker info
      get-content .\dockerfile.platform | docker build -
      docker images list
      get-content .\dockerfile.noplatform | docker build -
      docker images list
    displayName: 'Run all-the-things!'

