# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: WindowsNoPlatform
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker info
      docker images list
      get-content .\dockerfile.noplatform | docker build -
      docker images list
    displayName: 'Run all-the-things!'
- job: WindowsPlatform
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      docker info
      docker images list
      get-content .\dockerfile.platform | docker build -
      docker images list
    displayName: 'Run all-the-things!'
- job: WindowsPlatformPlusOne
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      # https://www.altaro.com/msp-dojo/linux-containers-windows-server-2019/
      [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
      Restart-Service docker

      docker info
      docker images list
      get-content .\dockerfile.platform | docker build -
      docker images list
    displayName: 'Run all-the-things!'
- job: WindowsPlatformPlusTwo
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      # https://computingforgeeks.com/how-to-run-docker-containers-on-windows-server-2019/
      Uninstall-Package -Name docker -ProviderName DockerMSFTProvider
      Get-VM WinContainerHost | Set-VMProcessor -ExposeVirtualizationExtensions $true
      Install-Module DockerProvider
      Install-Package Docker -ProviderName DockerProvider -RequiredVersion preview

      [Environment]::SetEnvironmentVariable("LCOW_SUPPORTED", "1", "Machine")
      Restart-Service docker

      docker info
      docker images list
      get-content .\dockerfile.platform | docker build -
      docker images list
    displayName: 'Run all-the-things!'

